version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mywebapp_db
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - mywebapp_default

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mywebapp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mywebapp_default

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    networks:
      - mywebapp_default

volumes:
  postgres_data:

networks:
  mywebapp_default:
    name: mywebapp_default
